### PR TITLE
Added a contributing.md

### PR DESCRIPTION
**Pull request by heysagnik**
This will help the open source developers who are looking to contribute to the project

### CODE REVIEW

**Review by karthikscale3 — APPROVED** [review]
Thank you for adding this

**Comment by heysagnik** [comment]
Could you please add hacktoberfest-accepted tag please

**Comment by karthikscale3** [comment]
> Could you please add hacktoberfest-accepted tag please

where exactly do i put this?

**Comment by heysagnik** [comment]
> > Could you please add hacktoberfest-accepted tag please
> 
> where exactly do i put this?

In this PR , see there you can add tags , type hacktoberfest-accepted and then create new tag if not made previously and you add the tag

**Pull request merged**
